### ISSUE TITLE
Should I send a pull request?

### ISSUE THREAD

**Issue by Zombiesalad1337** [PankajzYadav/csgo_rank_finder#1]
I forked your repo and added functionality to also find valorant ranks. If you'd like it merged in your repo then you can let me know. Sorry for creating an issue, idk how to message/discuss on github.

**Comment by aimrao** [comment]
Hi, I went through your code and it looks good but there is one big difference between the way you are finding the valo ranks and me finding the csgo ranks, which is you have to type everyone's handle one by one and then the code will run which you can not do while playing in a match but in case of csgo I do not need to type anything, I just copy paste the list from the console and it works. I also want to extend its functionality for valorant but for that I need some API from riot which can provide the player handles in your current match adn therefore I am searching for some workarounds for achieving this. I hope you understand this point, also tracker.gg does not have data for all players, only players who have logged on to their website have their rank updated. 
P.S. time.sleep(2) is there so that the server does not keep blocking the scraper if you continuously try to scrape it.

**Comment by Zombiesalad1337** [comment]
Yeah, thanks for your input! Not having an in-game console sucks.
